first_name = input('Write first name:')
last_name = input('last name: ')
course_name = input('Input course name: ')
numb_learners = input('Number of participants: ')

print('My name is', end=' ')
print(first_name, end=' ')
print('with last name', end=' ')
print(last_name, end=', ')
print('I am participating in the course', end=' ')
print(course_name, end='. ')
print('There are', end=' ')
print(numb_learners, end=' ')
print('candidates taking the course.')