def say_my_name():
    
    print(r"""          .--.  ,---.  ,-..-. .-.   .---.           
    |\    /| / /\ \ | .-.\ |(|| | | |  ( .-._)          
    |(\  / |/ /__\ \| `-'/ (_)| | | | (_) \             
    (_)\/  ||  __  ||   (  | || | | | _  \ \            
    | \  / || |  |)|| |\ \ | || `-')|( `-'  )           
    | |\/| ||_|  (_)|_| \)\`-'`---(_) `----'            
    '-'  '-'            (__)                            
    ,'|"\.-.   .-.,---.    .---. ,---. _______ .-. .-. 
    | |\ \\ \_/ )/| .-.\  ( .-._)| .-'|__   __|| | | | 
    | | \ \\   (_)| `-'/ (_) \   | `-.  )| |   | `-' | 
    | |  \ \) (   |   (  _  \ \  | .-' (_) |   | .-. | 
    /(|`-' /| |   | |\ \( `-'  ) |  `--. | |   | | |)| 
    (__)`--'/(_|   |_| \)\`----'  /( __.' `-'   /(  (_) 
        (__)        (__)      (__)          (__)     """
    )
    

def hei(a):
    """_summary_

    Args:
        a (_type_): _description_
        hei takes an argument 

    Returns:
        _type_: _description_ a is returned!
    """
    return a

#a)
# Go to ex2_str.docx exercise 1 (related to
# ex1_print_and_var.docx exercise 2) and encapsulate
# the code in function called “say_my_name()” which
# has no input and no output, but should print you
# name in a cool format.
# Call the function and verify that it works.

say_my_name()
hei(say_my_name())
#b)
# Do a minimal effort documentation of the function
# autogenerated by you editor, or format as we showed
# in class. 
